server:
  port: 2001

spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos服务注册地址
        group: yan-dev  #服务注册分组
        #service: mall-coupon #注册在nacos-server中的名字，等同于 spring.application.name
  application:
    name: mall-member #服务名称，在nacos中会展示出来

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  #扫描mapper文件
  global-config:
    db-config:
      id-type: auto #设置主键自增